# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin
  password: admin

development:
  <<: *default
  adapter: postgresql
  database: webshop_development
  username: admin
  password: admin
  host: localhost

test:
  <<: *default
  adapter: postgresql
  username: admin
  password: admin

production:
  <<: *default
  adapter: postgresql
  database: webshop_production
  username: webshop
  password: <%= ENV['WEBSHOP_DATABASE_PASSWORD'] %>
